[2024-02-05T19:25:31.098+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Danalysis_json_processing_dag.extract_data_task manual__2024-02-05T19:20:17.205359+00:00 [queued]>
[2024-02-05T19:25:31.120+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Danalysis_json_processing_dag.extract_data_task manual__2024-02-05T19:20:17.205359+00:00 [queued]>
[2024-02-05T19:25:31.123+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-05T19:25:31.153+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_data_task> on 2024-02-05 19:20:17.205359+00:00
[2024-02-05T19:25:31.163+0000] {standard_task_runner.py:60} INFO - Started process 2349 to run task
[2024-02-05T19:25:31.179+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Danalysis_json_processing_dag', 'extract_data_task', 'manual__2024-02-05T19:20:17.205359+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/danalysis_dag.py', '--cfg-path', '/tmp/tmpvbxmq4t0']
[2024-02-05T19:25:31.184+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask extract_data_task
[2024-02-05T19:25:31.284+0000] {task_command.py:423} INFO - Running <TaskInstance: Danalysis_json_processing_dag.extract_data_task manual__2024-02-05T19:20:17.205359+00:00 [running]> on host d3f529db5c6c
[2024-02-05T19:25:31.513+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='amukayoung@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Danalysis_json_processing_dag' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T19:20:17.205359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-05T19:20:17.205359+00:00'
[2024-02-05T19:25:31.522+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract_data() missing 1 required positional argument: 'data'
[2024-02-05T19:25:31.581+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Danalysis_json_processing_dag, task_id=extract_data_task, execution_date=20240205T192017, start_date=20240205T192531, end_date=20240205T192531
[2024-02-05T19:25:31.606+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task extract_data_task (extract_data() missing 1 required positional argument: 'data'; 2349)
[2024-02-05T19:25:31.638+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T19:25:31.684+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
